name: build

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:

env:
  version: "1.0.${{ github.run_number }}${{ github.run_attempt }}"
  package_name: ProcessTracker
  rpm_arch: x86_64
  rpm_release: 1

jobs:
  build-matrix:
    strategy:
      matrix:
        build_runtime: 
          - linux-x64
    
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      
    env:
      build_configuration: Release
      build_framework: net8.0
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
      
    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build
      
    - name: dotnet publish
      run: dotnet publish --configuration ${{ env.build_configuration }} --runtime ${{ matrix.build_runtime }} --framework ${{ env.build_framework }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=false -p:PublishReadyToRun=false -p:Version=${{ env.version }} -p:PackageVersion=${{ env.version }} --output publish

    - name: Set execute permissoins
      run: |
        cd "${{ github.workspace }}/publish/"
        chmod +x ProcessTracker

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/publish