name: update-nix-flake

on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  dotnet_major: 9
  build_framework: net9.0
  build_configuration: Release

jobs:
  build:
    strategy:
      matrix:
        build_runtime: 
          - linux-x64
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet_major }}
      
    - name: dotnet restore
      run: dotnet restore --runtime ${{ matrix.build_runtime }} --packages nuget-restore ./ProcessTracker.sln

    - name: create dependency file
      run: |
        nix shell nixpkgs#nuget-to-json nixpkgs#dotnetCorePackages.sdk_9_0 --command sh -c "nuget-to-json nuget-restore/ > deps.json"
        rm -r nuget-restore
        cat deps.json

    - name: configure git
      run: |
        git config user.email flake-update@dummy.com
        git config user.name flake-update

    - name: create branch
      run: git checkout -b "flake-update-${{ github.run_number }}-${{ github.run_attempt }}"

    - name: check git status
      run: git status

    - name: stage changes
      run: |
        git add deps.json
        git add flake.nix
        git add flake.lock
        git status

    - name: commit changes
      run: |
        git commit -m "Update nix flake"
        git push --set-upstream origin flake-update-${{ github.run_number }}-${{ github.run_attempt }}

    - name: create pull request
      run: gh pr create -B main -H "flake-update-${{ github.run_number }}-${{ github.run_attempt }}" --title 'Update nix flake' --body 'Updated nix flake'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
